from source.header_operations import *

from source.module_constants import *


scripts = [

  #script_game_quick_start
  # This script is called from the game engine for initializing the global variables for tutorial, multiplayer and custom battle modes.
  # INPUT:
  # none
  # OUTPUT:
  # none
  ("game_quick_start",
    [
      #for quick battle mode
      (assign, "$g_is_quick_battle", 0),
      (assign, "$g_quick_battle_game_type", 0),
      (assign, "$g_quick_battle_troop", quick_battle_troops_begin),
      (assign, "$g_quick_battle_map", quick_battle_scenes_begin),
      (assign, "$g_quick_battle_team_1_faction", "fac_kingdom_1"),
      (assign, "$g_quick_battle_team_2_faction", "fac_kingdom_2"),
      (assign, "$g_quick_battle_army_1_size", 25),
      (assign, "$g_quick_battle_army_2_size", 25),

      (faction_set_slot, "fac_outlaws", "slot_faction_quick_battle_tier_1_infantry", "trp_mountain_bandit"),
      (faction_set_slot, "fac_outlaws", "slot_faction_quick_battle_tier_2_infantry", "trp_sea_raider"),
      (faction_set_slot, "fac_outlaws", "slot_faction_quick_battle_tier_1_archer", "trp_forest_bandit"),
      (faction_set_slot, "fac_outlaws", "slot_faction_quick_battle_tier_2_archer", "trp_taiga_bandit"),
      (faction_set_slot, "fac_outlaws", "slot_faction_quick_battle_tier_1_cavalry", "trp_steppe_bandit"),
      (faction_set_slot, "fac_outlaws", "slot_faction_quick_battle_tier_2_cavalry", "trp_desert_bandit"),
      (faction_set_slot, "fac_kingdom_1", "slot_faction_quick_battle_tier_1_infantry", "trp_jute_skirmishert3"),
      (faction_set_slot, "fac_kingdom_1", "slot_faction_quick_battle_tier_2_infantry", "trp_jute_infantryt3"),
      (faction_set_slot, "fac_kingdom_1", "slot_faction_quick_battle_tier_1_archer", "trp_jute_archert1"),
      (faction_set_slot, "fac_kingdom_1", "slot_faction_quick_battle_tier_2_archer", "trp_jute_skirmishert4"),
      (faction_set_slot, "fac_kingdom_1", "slot_faction_quick_battle_tier_1_cavalry", "trp_jute_horsemant4"),
      (faction_set_slot, "fac_kingdom_1", "slot_faction_quick_battle_tier_2_cavalry", "trp_jute_skirmishert5"),
      (faction_set_slot, "fac_kingdom_2", "slot_faction_quick_battle_tier_1_infantry", "trp_saxon_skirmishert3"),
      (faction_set_slot, "fac_kingdom_2", "slot_faction_quick_battle_tier_2_infantry", "trp_saxon_infantryt3"),
      (faction_set_slot, "fac_kingdom_2", "slot_faction_quick_battle_tier_1_archer", "trp_saxon_archer"),
      (faction_set_slot, "fac_kingdom_2", "slot_faction_quick_battle_tier_2_archer", "trp_saxon_skirmishert4"),
      (faction_set_slot, "fac_kingdom_2", "slot_faction_quick_battle_tier_1_cavalry", "trp_saxon_horseman1"),
      (faction_set_slot, "fac_kingdom_2", "slot_faction_quick_battle_tier_2_cavalry", "trp_saxon_skirmishert5"),
      (faction_set_slot, "fac_kingdom_3", "slot_faction_quick_battle_tier_1_infantry", "trp_saxon_skirmishert3"),
      (faction_set_slot, "fac_kingdom_3", "slot_faction_quick_battle_tier_2_infantry", "trp_saxon_infantryt3"),
      (faction_set_slot, "fac_kingdom_3", "slot_faction_quick_battle_tier_1_archer", "trp_saxon_archer"),
      (faction_set_slot, "fac_kingdom_3", "slot_faction_quick_battle_tier_2_archer", "trp_saxon_skirmishert4"),
      (faction_set_slot, "fac_kingdom_3", "slot_faction_quick_battle_tier_1_cavalry", "trp_saxon_horseman1"),
      (faction_set_slot, "fac_kingdom_3", "slot_faction_quick_battle_tier_2_cavalry", "trp_saxon_skirmishert5"),
      (faction_set_slot, "fac_kingdom_4", "slot_faction_quick_battle_tier_1_infantry", "trp_engle_skirmishert3"),
      (faction_set_slot, "fac_kingdom_4", "slot_faction_quick_battle_tier_2_infantry", "trp_engle_infantryt3"),
      (faction_set_slot, "fac_kingdom_4", "slot_faction_quick_battle_tier_1_archer", "trp_engle_archer"),
      (faction_set_slot, "fac_kingdom_4", "slot_faction_quick_battle_tier_2_archer", "trp_engle_skirmishert4"),
      (faction_set_slot, "fac_kingdom_4", "slot_faction_quick_battle_tier_1_cavalry", "trp_engle_horseman"),
      (faction_set_slot, "fac_kingdom_4", "slot_faction_quick_battle_tier_2_cavalry", "trp_engle_skirmishert5"),
      (faction_set_slot, "fac_kingdom_5", "slot_faction_quick_battle_tier_1_infantry", "trp_saxon_skirmishert3"),
      (faction_set_slot, "fac_kingdom_5", "slot_faction_quick_battle_tier_2_infantry", "trp_saxon_infantryt3"),
      (faction_set_slot, "fac_kingdom_5", "slot_faction_quick_battle_tier_1_archer", "trp_saxon_archer"),
      (faction_set_slot, "fac_kingdom_5", "slot_faction_quick_battle_tier_2_archer", "trp_saxon_skirmishert4"),
      (faction_set_slot, "fac_kingdom_5", "slot_faction_quick_battle_tier_1_cavalry", "trp_saxon_horseman1"),
      (faction_set_slot, "fac_kingdom_5", "slot_faction_quick_battle_tier_2_cavalry", "trp_saxon_skirmishert5"),
      (faction_set_slot, "fac_kingdom_6", "slot_faction_quick_battle_tier_1_infantry", "trp_briton_infantryt3"),
      (faction_set_slot, "fac_kingdom_6", "slot_faction_quick_battle_tier_2_infantry", "trp_briton_skirmt3"),
      (faction_set_slot, "fac_kingdom_6", "slot_faction_quick_battle_tier_1_archer", "trp_briton_archer"),
      (faction_set_slot, "fac_kingdom_6", "slot_faction_quick_battle_tier_2_archer", "trp_briton_longbowman"),
      (faction_set_slot, "fac_kingdom_6", "slot_faction_quick_battle_tier_1_cavalry", "trp_briton_cavalry"),
      (faction_set_slot, "fac_kingdom_6", "slot_faction_quick_battle_tier_2_cavalry", "trp_briton_horseman"),
      (faction_set_slot, "fac_kingdom_7", "slot_faction_quick_battle_tier_1_infantry", "trp_briton_infantryt3"),
      (faction_set_slot, "fac_kingdom_7", "slot_faction_quick_battle_tier_2_infantry", "trp_briton_skirmt3"),
      (faction_set_slot, "fac_kingdom_7", "slot_faction_quick_battle_tier_1_archer", "trp_briton_archer"),
      (faction_set_slot, "fac_kingdom_7", "slot_faction_quick_battle_tier_2_archer", "trp_briton_longbowman"),
      (faction_set_slot, "fac_kingdom_7", "slot_faction_quick_battle_tier_1_cavalry", "trp_briton_cavalry"),
      (faction_set_slot, "fac_kingdom_7", "slot_faction_quick_battle_tier_2_cavalry", "trp_briton_horseman"),
      (faction_set_slot, "fac_kingdom_8", "slot_faction_quick_battle_tier_1_infantry", "trp_briton_infantryt3"),
      (faction_set_slot, "fac_kingdom_8", "slot_faction_quick_battle_tier_2_infantry", "trp_briton_skirmt3"),
      (faction_set_slot, "fac_kingdom_8", "slot_faction_quick_battle_tier_1_archer", "trp_briton_archer"),
      (faction_set_slot, "fac_kingdom_8", "slot_faction_quick_battle_tier_2_archer", "trp_briton_longbowman"),
      (faction_set_slot, "fac_kingdom_8", "slot_faction_quick_battle_tier_1_cavalry", "trp_briton_cavalry"),
      (faction_set_slot, "fac_kingdom_8", "slot_faction_quick_battle_tier_2_cavalry", "trp_briton_horseman"),
      (faction_set_slot, "fac_kingdom_9", "slot_faction_quick_battle_tier_1_infantry", "trp_engle_skirmishert3"),
      (faction_set_slot, "fac_kingdom_9", "slot_faction_quick_battle_tier_2_infantry", "trp_engle_infantryt3"),
      (faction_set_slot, "fac_kingdom_9", "slot_faction_quick_battle_tier_1_archer", "trp_engle_archer"),
      (faction_set_slot, "fac_kingdom_9", "slot_faction_quick_battle_tier_2_archer", "trp_engle_skirmishert4"),
      (faction_set_slot, "fac_kingdom_9", "slot_faction_quick_battle_tier_1_cavalry", "trp_engle_horseman"),
      (faction_set_slot, "fac_kingdom_9", "slot_faction_quick_battle_tier_2_cavalry", "trp_engle_skirmishert5"),
      (faction_set_slot, "fac_kingdom_10", "slot_faction_quick_battle_tier_1_infantry", "trp_briton_infantryt3"),
      (faction_set_slot, "fac_kingdom_10", "slot_faction_quick_battle_tier_2_infantry", "trp_briton_skirmt3"),
      (faction_set_slot, "fac_kingdom_10", "slot_faction_quick_battle_tier_1_archer", "trp_briton_archer"),
      (faction_set_slot, "fac_kingdom_10", "slot_faction_quick_battle_tier_2_archer", "trp_briton_longbowman"),
      (faction_set_slot, "fac_kingdom_10", "slot_faction_quick_battle_tier_1_cavalry", "trp_briton_cavalry"),
      (faction_set_slot, "fac_kingdom_10", "slot_faction_quick_battle_tier_2_cavalry", "trp_briton_horseman"),
      (faction_set_slot, "fac_kingdom_11", "slot_faction_quick_battle_tier_1_infantry", "trp_briton_infantryt3"),
      (faction_set_slot, "fac_kingdom_11", "slot_faction_quick_battle_tier_2_infantry", "trp_briton_skirmt3"),
      (faction_set_slot, "fac_kingdom_11", "slot_faction_quick_battle_tier_1_archer", "trp_briton_archer"),
      (faction_set_slot, "fac_kingdom_11", "slot_faction_quick_battle_tier_2_archer", "trp_briton_longbowman"),
      (faction_set_slot, "fac_kingdom_11", "slot_faction_quick_battle_tier_1_cavalry", "trp_briton_cavalry"),
      (faction_set_slot, "fac_kingdom_11", "slot_faction_quick_battle_tier_2_cavalry", "trp_briton_horseman"),
      (faction_set_slot, "fac_kingdom_12", "slot_faction_quick_battle_tier_1_infantry", "trp_briton_infantryt3"),
      (faction_set_slot, "fac_kingdom_12", "slot_faction_quick_battle_tier_2_infantry", "trp_briton_skirmt3"),
      (faction_set_slot, "fac_kingdom_12", "slot_faction_quick_battle_tier_1_archer", "trp_briton_archer"),
      (faction_set_slot, "fac_kingdom_12", "slot_faction_quick_battle_tier_2_archer", "trp_briton_longbowman"),
      (faction_set_slot, "fac_kingdom_12", "slot_faction_quick_battle_tier_1_cavalry", "trp_briton_cavalry"),
      (faction_set_slot, "fac_kingdom_12", "slot_faction_quick_battle_tier_2_cavalry", "trp_briton_horseman"),
      (faction_set_slot, "fac_kingdom_13", "slot_faction_quick_battle_tier_1_infantry", "trp_engle_skirmishert3"),
      (faction_set_slot, "fac_kingdom_13", "slot_faction_quick_battle_tier_2_infantry", "trp_engle_infantryt3"),
      (faction_set_slot, "fac_kingdom_13", "slot_faction_quick_battle_tier_1_archer", "trp_engle_archer"),
      (faction_set_slot, "fac_kingdom_13", "slot_faction_quick_battle_tier_2_archer", "trp_engle_skirmishert4"),
      (faction_set_slot, "fac_kingdom_13", "slot_faction_quick_battle_tier_1_cavalry", "trp_engle_horseman"),
      (faction_set_slot, "fac_kingdom_13", "slot_faction_quick_battle_tier_2_cavalry", "trp_engle_skirmishert5"),
      (faction_set_slot, "fac_kingdom_14", "slot_faction_quick_battle_tier_1_infantry", "trp_engle_skirmishert3"),
      (faction_set_slot, "fac_kingdom_14", "slot_faction_quick_battle_tier_2_infantry", "trp_engle_infantryt3"),
      (faction_set_slot, "fac_kingdom_14", "slot_faction_quick_battle_tier_1_archer", "trp_engle_archer"),
      (faction_set_slot, "fac_kingdom_14", "slot_faction_quick_battle_tier_2_archer", "trp_engle_skirmishert4"),
      (faction_set_slot, "fac_kingdom_14", "slot_faction_quick_battle_tier_1_cavalry", "trp_engle_horseman"),
      (faction_set_slot, "fac_kingdom_14", "slot_faction_quick_battle_tier_2_cavalry", "trp_engle_skirmishert5"),
      (faction_set_slot, "fac_kingdom_15", "slot_faction_quick_battle_tier_1_infantry", "trp_briton_infantryt3"),
      (faction_set_slot, "fac_kingdom_15", "slot_faction_quick_battle_tier_2_infantry", "trp_briton_skirmt3"),
      (faction_set_slot, "fac_kingdom_15", "slot_faction_quick_battle_tier_1_archer", "trp_briton_archer"),
      (faction_set_slot, "fac_kingdom_15", "slot_faction_quick_battle_tier_2_archer", "trp_briton_longbowman"),
      (faction_set_slot, "fac_kingdom_15", "slot_faction_quick_battle_tier_1_cavalry", "trp_briton_cavalry"),
      (faction_set_slot, "fac_kingdom_15", "slot_faction_quick_battle_tier_2_cavalry", "trp_briton_horseman"),
      (faction_set_slot, "fac_kingdom_16", "slot_faction_quick_battle_tier_1_infantry", "trp_briton_infantryt3"),
      (faction_set_slot, "fac_kingdom_16", "slot_faction_quick_battle_tier_2_infantry", "trp_briton_skirmt3"),
      (faction_set_slot, "fac_kingdom_16", "slot_faction_quick_battle_tier_1_archer", "trp_briton_archer"),
      (faction_set_slot, "fac_kingdom_16", "slot_faction_quick_battle_tier_2_archer", "trp_briton_longbowman"),
      (faction_set_slot, "fac_kingdom_16", "slot_faction_quick_battle_tier_1_cavalry", "trp_briton_cavalry"),
      (faction_set_slot, "fac_kingdom_16", "slot_faction_quick_battle_tier_2_cavalry", "trp_briton_horseman"),
      (faction_set_slot, "fac_kingdom_17", "slot_faction_quick_battle_tier_1_infantry", "trp_irish_infantryt3"),
      (faction_set_slot, "fac_kingdom_17", "slot_faction_quick_battle_tier_2_infantry", "trp_irish_skirmishert3"),
      (faction_set_slot, "fac_kingdom_17", "slot_faction_quick_battle_tier_1_archer", "trp_irish_infantryt4"),
      (faction_set_slot, "fac_kingdom_17", "slot_faction_quick_battle_tier_2_archer", "trp_irish_archer"),
      (faction_set_slot, "fac_kingdom_17", "slot_faction_quick_battle_tier_1_cavalry", "trp_irish_infantryt5"),
      (faction_set_slot, "fac_kingdom_17", "slot_faction_quick_battle_tier_2_cavalry", "trp_irish_horseman"),
      (faction_set_slot, "fac_kingdom_18", "slot_faction_quick_battle_tier_1_infantry", "trp_briton_infantryt3"),
      (faction_set_slot, "fac_kingdom_18", "slot_faction_quick_battle_tier_2_infantry", "trp_briton_skirmt3"),
      (faction_set_slot, "fac_kingdom_18", "slot_faction_quick_battle_tier_1_archer", "trp_briton_archer"),
      (faction_set_slot, "fac_kingdom_18", "slot_faction_quick_battle_tier_2_archer", "trp_briton_longbowman"),
      (faction_set_slot, "fac_kingdom_18", "slot_faction_quick_battle_tier_1_cavalry", "trp_briton_cavalry"),
      (faction_set_slot, "fac_kingdom_18", "slot_faction_quick_battle_tier_2_cavalry", "trp_briton_horseman"),
      (faction_set_slot, "fac_kingdom_19", "slot_faction_quick_battle_tier_1_infantry", "trp_irish_infantryt3"),
      (faction_set_slot, "fac_kingdom_19", "slot_faction_quick_battle_tier_2_infantry", "trp_irish_skirmishert3"),
      (faction_set_slot, "fac_kingdom_19", "slot_faction_quick_battle_tier_1_archer", "trp_irish_infantryt4"),
      (faction_set_slot, "fac_kingdom_19", "slot_faction_quick_battle_tier_2_archer", "trp_irish_archer"),
      (faction_set_slot, "fac_kingdom_19", "slot_faction_quick_battle_tier_1_cavalry", "trp_irish_infantryt5"),
      (faction_set_slot, "fac_kingdom_19", "slot_faction_quick_battle_tier_2_cavalry", "trp_irish_horseman"),
      (faction_set_slot, "fac_kingdom_20", "slot_faction_quick_battle_tier_1_infantry", "trp_pict_horsesquiret3"),
      (faction_set_slot, "fac_kingdom_20", "slot_faction_quick_battle_tier_2_infantry", "trp_pict_skirmishert4"),
      (faction_set_slot, "fac_kingdom_20", "slot_faction_quick_battle_tier_1_archer", "trp_pict_skirmishert4"),
      (faction_set_slot, "fac_kingdom_20", "slot_faction_quick_battle_tier_2_archer", "trp_pict_archer"),
      (faction_set_slot, "fac_kingdom_20", "slot_faction_quick_battle_tier_1_cavalry", "trp_pict_horseman"),
      (faction_set_slot, "fac_kingdom_20", "slot_faction_quick_battle_tier_2_cavalry", "trp_pict_noblecavalry"),
      (faction_set_slot, "fac_kingdom_21", "slot_faction_quick_battle_tier_1_infantry", "trp_briton_infantryt3"),
      (faction_set_slot, "fac_kingdom_21", "slot_faction_quick_battle_tier_2_infantry", "trp_briton_skirmt3"),
      (faction_set_slot, "fac_kingdom_21", "slot_faction_quick_battle_tier_1_archer", "trp_briton_archer"),
      (faction_set_slot, "fac_kingdom_21", "slot_faction_quick_battle_tier_2_archer", "trp_briton_longbowman"),
      (faction_set_slot, "fac_kingdom_21", "slot_faction_quick_battle_tier_1_cavalry", "trp_briton_cavalry"),
      (faction_set_slot, "fac_kingdom_21", "slot_faction_quick_battle_tier_2_cavalry", "trp_briton_horseman"),
      (faction_set_slot, "fac_kingdom_22", "slot_faction_quick_battle_tier_1_infantry", "trp_briton_infantryt3"),
      (faction_set_slot, "fac_kingdom_22", "slot_faction_quick_battle_tier_2_infantry", "trp_briton_skirmt3"),
      (faction_set_slot, "fac_kingdom_22", "slot_faction_quick_battle_tier_1_archer", "trp_briton_archer"),
      (faction_set_slot, "fac_kingdom_22", "slot_faction_quick_battle_tier_2_archer", "trp_briton_longbowman"),
      (faction_set_slot, "fac_kingdom_22", "slot_faction_quick_battle_tier_1_cavalry", "trp_briton_cavalry"),
      (faction_set_slot, "fac_kingdom_22", "slot_faction_quick_battle_tier_2_cavalry", "trp_briton_horseman"),
      (faction_set_slot, "fac_kingdom_23", "slot_faction_quick_battle_tier_1_infantry", "trp_briton_infantryt3"),
      (faction_set_slot, "fac_kingdom_23", "slot_faction_quick_battle_tier_2_infantry", "trp_briton_skirmt3"),
      (faction_set_slot, "fac_kingdom_23", "slot_faction_quick_battle_tier_1_archer", "trp_briton_archer"),
      (faction_set_slot, "fac_kingdom_23", "slot_faction_quick_battle_tier_2_archer", "trp_briton_longbowman"),
      (faction_set_slot, "fac_kingdom_23", "slot_faction_quick_battle_tier_1_cavalry", "trp_briton_cavalry"),
      (faction_set_slot, "fac_kingdom_23", "slot_faction_quick_battle_tier_2_cavalry", "trp_briton_horseman"),
      (faction_set_slot, "fac_kingdom_24", "slot_faction_quick_battle_tier_1_infantry", "trp_briton_infantryt3"),
      (faction_set_slot, "fac_kingdom_24", "slot_faction_quick_battle_tier_2_infantry", "trp_briton_skirmt3"),
      (faction_set_slot, "fac_kingdom_24", "slot_faction_quick_battle_tier_1_archer", "trp_briton_archer"),
      (faction_set_slot, "fac_kingdom_24", "slot_faction_quick_battle_tier_2_archer", "trp_briton_longbowman"),
      (faction_set_slot, "fac_kingdom_24", "slot_faction_quick_battle_tier_1_cavalry", "trp_briton_cavalry"),
      (faction_set_slot, "fac_kingdom_24", "slot_faction_quick_battle_tier_2_cavalry", "trp_briton_horseman"),
      (faction_set_slot, "fac_kingdom_25", "slot_faction_quick_battle_tier_1_infantry", "trp_briton_infantryt3"),
      (faction_set_slot, "fac_kingdom_25", "slot_faction_quick_battle_tier_2_infantry", "trp_briton_skirmt3"),
      (faction_set_slot, "fac_kingdom_25", "slot_faction_quick_battle_tier_1_archer", "trp_briton_archer"),
      (faction_set_slot, "fac_kingdom_25", "slot_faction_quick_battle_tier_2_archer", "trp_briton_longbowman"),
      (faction_set_slot, "fac_kingdom_25", "slot_faction_quick_battle_tier_1_cavalry", "trp_briton_cavalry"),
      (faction_set_slot, "fac_kingdom_25", "slot_faction_quick_battle_tier_2_cavalry", "trp_briton_horseman"),
      (faction_set_slot, "fac_kingdom_26", "slot_faction_quick_battle_tier_1_infantry", "trp_briton_infantryt3"),
      (faction_set_slot, "fac_kingdom_26", "slot_faction_quick_battle_tier_2_infantry", "trp_briton_skirmt3"),
      (faction_set_slot, "fac_kingdom_26", "slot_faction_quick_battle_tier_1_archer", "trp_briton_archer"),
      (faction_set_slot, "fac_kingdom_26", "slot_faction_quick_battle_tier_2_archer", "trp_briton_longbowman"),
      (faction_set_slot, "fac_kingdom_26", "slot_faction_quick_battle_tier_1_cavalry", "trp_briton_cavalry"),
      (faction_set_slot, "fac_kingdom_26", "slot_faction_quick_battle_tier_2_cavalry", "trp_briton_horseman"),
      (faction_set_slot, "fac_kingdom_27", "slot_faction_quick_battle_tier_1_infantry", "trp_irish_infantryt3"),
      (faction_set_slot, "fac_kingdom_27", "slot_faction_quick_battle_tier_2_infantry", "trp_irish_skirmishert3"),
      (faction_set_slot, "fac_kingdom_27", "slot_faction_quick_battle_tier_1_archer", "trp_irish_infantryt4"),
      (faction_set_slot, "fac_kingdom_27", "slot_faction_quick_battle_tier_2_archer", "trp_irish_archer"),
      (faction_set_slot, "fac_kingdom_27", "slot_faction_quick_battle_tier_1_cavalry", "trp_irish_infantryt5"),
      (faction_set_slot, "fac_kingdom_27", "slot_faction_quick_battle_tier_2_cavalry", "trp_irish_horseman"),
      (faction_set_slot, "fac_kingdom_28", "slot_faction_quick_battle_tier_1_infantry", "trp_irish_infantryt3"),
      (faction_set_slot, "fac_kingdom_28", "slot_faction_quick_battle_tier_2_infantry", "trp_irish_skirmishert3"),
      (faction_set_slot, "fac_kingdom_28", "slot_faction_quick_battle_tier_1_archer", "trp_irish_infantryt4"),
      (faction_set_slot, "fac_kingdom_28", "slot_faction_quick_battle_tier_2_archer", "trp_irish_archer"),
      (faction_set_slot, "fac_kingdom_28", "slot_faction_quick_battle_tier_1_cavalry", "trp_irish_infantryt5"),
      (faction_set_slot, "fac_kingdom_28", "slot_faction_quick_battle_tier_2_cavalry", "trp_irish_horseman"),
      (faction_set_slot, "fac_kingdom_29", "slot_faction_quick_battle_tier_1_infantry", "trp_irish_infantryt3"),
      (faction_set_slot, "fac_kingdom_29", "slot_faction_quick_battle_tier_2_infantry", "trp_irish_skirmishert3"),
      (faction_set_slot, "fac_kingdom_29", "slot_faction_quick_battle_tier_1_archer", "trp_irish_infantryt4"),
      (faction_set_slot, "fac_kingdom_29", "slot_faction_quick_battle_tier_2_archer", "trp_irish_archer"),
      (faction_set_slot, "fac_kingdom_29", "slot_faction_quick_battle_tier_1_cavalry", "trp_irish_infantryt5"),
      (faction_set_slot, "fac_kingdom_29", "slot_faction_quick_battle_tier_2_cavalry", "trp_irish_horseman"),
      (faction_set_slot, "fac_kingdom_30", "slot_faction_quick_battle_tier_1_infantry", "trp_irish_infantryt3"),
      (faction_set_slot, "fac_kingdom_30", "slot_faction_quick_battle_tier_2_infantry", "trp_irish_skirmishert3"),
      (faction_set_slot, "fac_kingdom_30", "slot_faction_quick_battle_tier_1_archer", "trp_irish_infantryt4"),
      (faction_set_slot, "fac_kingdom_30", "slot_faction_quick_battle_tier_2_archer", "trp_irish_archer"),
      (faction_set_slot, "fac_kingdom_30", "slot_faction_quick_battle_tier_1_cavalry", "trp_irish_infantryt5"),
      (faction_set_slot, "fac_kingdom_30", "slot_faction_quick_battle_tier_2_cavalry", "trp_irish_horseman"),
      (faction_set_slot, "fac_kingdom_31", "slot_faction_quick_battle_tier_1_infantry", "trp_irish_infantryt3"),
      (faction_set_slot, "fac_kingdom_31", "slot_faction_quick_battle_tier_2_infantry", "trp_irish_skirmishert3"),
      (faction_set_slot, "fac_kingdom_31", "slot_faction_quick_battle_tier_1_archer", "trp_irish_infantryt4"),
      (faction_set_slot, "fac_kingdom_31", "slot_faction_quick_battle_tier_2_archer", "trp_irish_archer"),
      (faction_set_slot, "fac_kingdom_31", "slot_faction_quick_battle_tier_1_cavalry", "trp_irish_infantryt5"),
      (faction_set_slot, "fac_kingdom_31", "slot_faction_quick_battle_tier_2_cavalry", "trp_irish_horseman"),
#chief elige hasta aqui las tropas para batalla rapida

        (call_script, "script_initialize_multiplayer"),
    ]),
]
